package rules.example.flow

/**
 * 长城爱永随终身寿险/00005 交费期限 1 第一年
 */

rule "flow_insurance_00001_00320_paymentPeriod_1_time_1"
	ruleflow-group "insurancFlow_00001_00320_group"
	when
		insurance : LongTermInsuranceMainFlow( code == "00320" &&  paymentPeriod == 1 && time == 1)
	then
		// 基本费率
		insurance.setBaseFeeRate(new java.math.BigDecimal("0.044"));
		// 计算基本手续费 
		insurance.setBaseFee(insurance.getMoney().multiply(insurance.getBaseFeeRate()));
end