package rules.example.flow

declare LongTermInsuranceMainFlow
	
	protocolNo : String
	
	/**
	 * 险种代码
	 */
	code : String
	/**
	 * 缴费期限
	 */
	paymentPeriod : Integer
	/**
	 * 交费次数 （首年 二年 三年 四年 五年）
	 */
	time : Integer
	/**
	 * 续期保费
	 */
	money : java.math.BigDecimal
	/**
	 * 基本手续费率
	 */
	baseFeeRate : java.math.BigDecimal
	/**
	 * 基本手续费
	 */
	baseFee : java.math.BigDecimal
	
	/**
	 *
	 */
	baseMoney : java.math.BigDecimal
	
	/**
	 *
	 */
	baseMoneyRate : java.math.BigDecimal
end 

/**
 * 长城爱永随终身寿险/00005 交费期限 1 第一年
 */

rule "flow_insurance_00001_00005_paymentPeriod_1_time_1"
	ruleflow-group "insurancFlow_00001_00005_group"
	when
		insurance : LongTermInsuranceMainFlow( code == "00005" &&  paymentPeriod == 1 && time == 1)
	then
		// 基本费率
		insurance.setBaseFeeRate(new java.math.BigDecimal("0.04"));
		// 计算基本手续费 
		insurance.setBaseFee(insurance.getMoney().multiply(insurance.getBaseFeeRate()));
end




